testing something

diff --git a/.github/workflows/ci-tests.yaml b/.github/workflows/ci-tests.yaml
--- a/.github/workflows/ci-tests.yaml
+++ b/.github/workflows/ci-tests.yaml
@@ -14,15 +14,27 @@ jobs:
       - name: Install dependencies
         run: npm install
         
-      - name: Run security audit
+      # - name: Run security audit
+      #   run: |
+      #     echo "Running npm audit..."
+      #     npm audit
+      #     if [ $? -ne 0 ]; then
+      #       echo "Security vulnerabilities found! Build failed."
+      #       exit 1
+      #     fi
+      #     echo "No vulnerabilities found. Security check passed."
+
+      - name: Run security audit 2
         run: |
           echo "Running npm audit..."
-          npm audit
-          if [ $? -ne 0 ]; then
+          if npm audit; then
+            echo "No vulnerabilities found. Security check passed."
+          else
             echo "Security vulnerabilities found! Build failed."
-            exit 1
+            return 1
           fi
-          echo "No vulnerabilities found. Security check passed."
+          
+
 
   unit-tests:
     runs-on: ubuntu-latest
